### ISSUE TITLE
Transaction

### ISSUE THREAD

**Issue by Grega25** [Conflux-Chain/sirius#346]
**Do you want to request a _feature_ or report a _bug_?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**If this is a associated bounty or submission, please add the url to it here.**

**Please mention other relevant information such as the browser version, and Operating System.**
https://www.confluxscan.io/transaction/0x96fa9ed2bfb0e81099bf6921ab9fe911d94d25e761050562fd674d9ed9e76db7

**Comment by Grega25** [comment]
Is any way to get this ?

**Comment by chain-txz** [comment]
> Is any way to get this ?

Excuse me，did you mean get "transaction detail"?

**Comment by boqiu** [comment]
@Grega25 Please clarify your problem clearly.

**Comment by jnoodle** [comment]
We have not received any more replies for a long time. This issue will be closed.
