### ISSUE TITLE
 First, HOW DO YOU GIVE THE POSSIBILITY OF CREATING AN OLD NUMBER WALLET.

### ISSUE THREAD

**Issue by Scalfhaiver** [Conflux-Chain/sirius#351]
I HAD THE UNCLE OF CREATING A WALLET FIRST IN BINANCE, OLD WALLET, AFTER UPDATE. I WILL GO TO YOU AND YOU WILL OFFER ME AN OLD WALLET, WITHOUT HAVING THE CFX IN FRONT, IN GOOD, MINING 1 DAY ATTENTION, WITHOUT TALKING THE 10 DAYS IN BINANCE.

I AM EXCUSE TO SAY BUT WHAT THE SERVICE AND SUPPORT YOU HAVE.

**Comment by boqiu** [comment]
@Scalfhaiver not quite understand your problem, does it have something to do with the blockchain explorer?

**Comment by Scalfhaiver** [comment]
CFX address must be base32-encoded(CIP-37) or hex40(starting with 0x1)
Minimum payout is 100 CFX


Wallet - Binance - 0x9de756bccf2684d702facc7dedb8a0dcf5c33232 - NanoPool -  16.695 CFX (POOL Mined) I cant withdrawn, because update all wallets. 

Create a New Wallet ConfluxPortal -  0x1e708d5063548847c520555ebc1e6ae5d6a76954


-> They update to this one   -   cfx:aamdnbyfubtzy3y4u7s5pu6e62u7pjegeenbsnz92f 





So i was using nanopool with binance wallet, until now didnt have any RED TIP, showing that I was farming for nothing, did i really lose this CFX? Or still is it possible to take them back?
Please Nano, i choose you for reason.



Is it possible to recieve thoses CFX from binance that i was farming ?
Did i really lose them? I was mining 5 days straight. 

What is the possibilites ?
Sent from iCloud

On April 11, 2021 at 7:54 PM, Bo QIU ***@***.***> wrote:






@Scalfhaiver not quite understand your problem, does it have something to do with the blockchain explorer?

**Comment by jnoodle** [comment]
![image](https://user-images.githubusercontent.com/1267447/114804546-06582680-9dd4-11eb-8a8c-8f677d6b4d7a.png)

I noticed that your address does have some CFX. 

There are some tips: Minimum payout is 100 CFX and CFX address must be base32-encoded(CIP-37) or hex40(starting with 0x1).

You might have to mine 100 CFX to get them. 

For more details, please contact Nanopool.

**Comment by Scalfhaiver** [comment]
If u learn about the adress i cant transfer isnt about minimum i cant change to 1
problem that i will not recive them. because of taht UPDATE CFX adress
Sent from iCloud

On April 14, 2021 at 3:24 PM, jnoodle ***@***.***> wrote:






I noticed that your address does have some CFX.

There are some tips: Minimum payout is 100 CFX and CFX address must be base32-encoded(CIP-37) or hex40(starting with 0x1).

You might have to mine 100 CFX to get them.

For more details, please contact Nanopool.

**Comment by jnoodle** [comment]
Confluxscan is used for blockchain data viewing by users. Only scan-related bugs, technical issues, or product recommendations are accepted here.  For questions about asset and community product usage, please go to the forum or discussion group of the relevant product for help.
