### ISSUE TITLE
CFX didn't received

### ISSUE THREAD

**Issue by yams42000** [Conflux-Chain/sirius#352]
**Do you want to request a _feature_ or report a _bug_?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**If this is a associated bounty or submission, please add the url to it here.**

**Please mention other relevant information such as the browser version, and Operating System.**

**Comment by yams42000** [comment]
I didn't received my CFX i have mined with nanopool, direct sent to my binance wallet but i have nothing...

**Comment by boqiu** [comment]
@yams42000 If so, you'd better to contact **nanopool** for more details. To mine CFX on Conflux network, you should configure a Conflux address (in base32 format), other than a Binance wallet address (in HEX format).

**Comment by menidi** [comment]
nanopool does not send to BEP20 - better create conflux portal wallet

**Comment by jnoodle** [comment]
Confluxscan is used for blockchain data viewing by users. Only scan-related bugs, technical issues, or product recommendations are accepted here.  For questions about asset and community product usage, please go to the forum or discussion group of the relevant product for help.
