### ISSUE TITLE
cfx:aafarzmb4n03wr8kr95dt9zgdhh3ap4wfjj5r0t34v adress ve txid 0x822008d7101752945011ef8313f96fe079e609efaa4ac32e8ac85e668b5aef84 are u cancel?

### ISSUE THREAD

**Issue by fatihdalgali** [Conflux-Chain/sirius#356]
**Do you want to request a _feature_ or report a _bug_?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**If this is a associated bounty or submission, please add the url to it here.**

**Please mention other relevant information such as the browser version, and Operating System.**

**Comment by fatihdalgali** [comment]
hi

**Comment by fatihdalgali** [comment]
0x822008d7101752945011ef8313f96fe079e609efaa4ac32e8ac85e668b5aef84 txid number. how ı cancel?

**Comment by jnoodle** [comment]
This transaction has been successful and cannot be canceled.

**Comment by jnoodle** [comment]
We have not received any more replies for a long time. This issue will be closed.
