### ISSUE TITLE
CFX TRANSFERİM 15 GÜNDÜR GELMEDİ

### ISSUE THREAD

**Issue by ramazan76** [Conflux-Chain/sirius#363]
0x8a3df38a7a559834ec1f79cd9a388d5c7d822c99

0xfc1d338265750f6acca836324ac2d72e780560fb87a3f87896c81d044c2c96b2 |  
-- | --

CFX TRANSFERİMİN İADE EDİLMESİNİ TALEP EDİYORUM

**Comment by chain-txz** [comment]
![image](https://user-images.githubusercontent.com/67582161/114805363-71562d00-9dd5-11eb-869a-9f2dc5acc09e.png)

Lütfen bana transferin nedenini söyle @ramazan76 

Genellikle yalnızca sözleşme sahibi para iadesi yapabilir

**Comment by ramazan76** [comment]
Yanlış Ağ üzerinde trasfer yaptım bu trasferi iptal etmek istiyorum
hesabıma para iadesini istiyorum


15 Nis 2021 Per, saat 05:34 tarihinde tangxuezhi ***@***.***>
şunu yazdı:

**Comment by jnoodle** [comment]
Blockchain cannot roll back confirmed transactions. Please carefully confirm the transaction information before submitting the transaction.
