### ISSUE TITLE
I mistakenly uploaded CFX to my account https://wallet.confluxscan.io/

### ISSUE THREAD

**Issue by MacMarMining** [Conflux-Chain/sirius#366]
**Do you want to request a _feature_ or report a _bug_?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**If this is a associated bounty or submission, please add the url to it here.**

**Please mention other relevant information such as the browser version, and Operating System.**

**Comment by MacMarMining** [comment]
349 / 5000
Wyniki tłumaczenia
I warmly welcome
I mistakenly uploaded CFX to my account
0x17ff93c59eacbe5756c1b6198d8cec933314ca52
currently it is no
cfx: aan99e8fx40n6z402g5bxdpp7wkxgfgmmj0n76gx3t
https://www.confluxscan.io/address/cfx:aan99e8fx40n6z402g5bxdpp7wkxgfgmmj0n76gx3t?accountAddress=cfx%3Aaan99e8fx40n6z402g5bxdpp7wkxngfgmmt0
How can these funds be recovered
greetings

**Comment by imran5713** [comment]
hi
i mistakenly withdraw my cfx to my binance account and yet not recieved.
please guid i can i recover this amount.https://www.confluxscan.io/address/cfx:aat2a79r7xp4mn2ebgm6u70y4ktkn4u6wjpyk53426?accountAddress=cfx%3Aaat2a79r7xp4mn2ebgm6u70y4ktkn4u6wjpyk53426

**Comment by jnoodle** [comment]
https://wallet.confluxscan.io/ has an announcement: The Web Wallet officially ceased maintenance on 2020.10.29.

If you have backed up your wallet’s private key or Keystore, you can try to restore it with ConfluxPortal.

Confluxscan is used for blockchain data viewing by users. Only scan-related bugs, technical issues, or product recommendations are accepted here.  For questions about asset and community product usage, please go to the forum or discussion group of the relevant product for help.
