### ISSUE TITLE
shuttleflow.io didnt execute my contract

### ISSUE THREAD

**Issue by menidi** [Conflux-Chain/sirius#367]
**Do you want to request a _feature_ or report a _bug_?** NO

**What is the current behavior?** shuttleflow.io didnt execute my contract

**If the current behavior is a bug, please provide the steps to reproduce.** I shuttled out CFX to metamask wallet and the contract was not executed but funds left the wallet

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**If this is a associated bounty or submission, please add the url to it here.**

https://confluxscan.io/transaction/0x8ce29b7e553daded19ad2d621bca0e908a4f4abc648e2ea545e2d23ad387bf41?tab=logs

**Please mention other relevant information such as the browser version, and Operating System.**

Chrome browser Version 89.0.4389.128

**Comment by jnoodle** [comment]
Confluxscan is used for blockchain data viewing by users. Only scan-related bugs, technical issues, or product recommendations are accepted here.  For questions about asset and community product usage, please go to the forum or discussion group of the relevant product for help.

You can try to feedback in shuttleflow forum: https://forum.conflux.fun/c/English/shuttleflow
