### ISSUE TITLE
Cfx Çekim Sorunu

### ISSUE THREAD

**Issue by Abdullah-cevik** [Conflux-Chain/sirius#373]
**Do you want to request a _feature_ or report a _bug_?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**If this is a associated bounty or submission, please add the url to it here.**

**Please mention other relevant information such as the browser version, and Operating System.**

Hello. I was going to send a CFX over Okex, but I couldn't. Help me recover my CFX coins. Here's txhash: 
0x8ff13f9466b770f836643984f3b43050b1c9eac1028c1cb7a8f5b81052b06597
Okex üzerinden binance adresime gönderiyordum. 25 gün oldu hala alamadım. Binance kotunu gelmediğini söylüyor. Ben ise coinlerimi şurada görüyorum. Okex hesabıma nasıl çekerim tekrar?
https://www.confluxscan.io/transaction/0x8ff13f9466b770f836643984f3b43050b1c9eac1028c1cb7a8f5b81052b06597

**Comment by Abdullah-cevik** [comment]
Okex üzerinden binance adresime gönderiyordum. 25 gün oldu hala alamadım. Binance kendisine gelmediğini söylüyor. Ben ise coinlerimi şurada görüyorum.
https://www.confluxscan.io/transaction/0x8ff13f9466b770f836643984f3b43050b1c9eac1028c1cb7a8f5b81052b06597

**Comment by Abdullah-cevik** [comment]
Bunları tekrar okex hesabıma nasıl çekerim?

**Comment by Abdullah-cevik** [comment]
@Pana @jnoodle @resodo @GuichiZhao

**Comment by jnoodle** [comment]
Confluxscan is used for blockchain data viewing by users. Only scan-related bugs, technical issues, or product recommendations are accepted here.  For questions about asset and community product usage, please go to the forum or discussion group of the relevant product for help.

You could ask Binance or Okex customer service.
