### ISSUE TITLE
 NANOPOOL CFX PAYMENT

### ISSUE THREAD

**Issue by IVTNI** [Conflux-Chain/sirius#376]
WITH MY BINANCE WALLET ACCOUNT, I MADE OVER HIVETOS UP TO 100 CFX BUT I HAVE NOT RECEIVED THIS I HAVE AN ERROR
CFX address must be base32-encoded(CIP-37) or hex40(starting with 0x1)
![nanopool](https://user-images.githubusercontent.com/83193992/116018105-fa792980-a649-11eb-8515-e3d0d5852e37.png)

**Comment by jnoodle** [comment]
Confluxscan is used for blockchain data viewing by users. Only scan-related bugs, technical issues, or product recommendations are accepted here.  For questions about asset and community product usage, please go to the forum or discussion group of the relevant product for help.
