### ISSUE TITLE
Как вернуть не правльно конвертировал  0x86dd6f9cb1cd08af13a03555cead9854b7bc2dc523bd7bc47e86ec910823f91f

### ISSUE THREAD

**Issue by DALLAR38** [Conflux-Chain/sirius#377]
**Do you want to request a _feature_ or report a _bug_?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**If this is a associated bounty or submission, please add the url to it here.**

**Please mention other relevant information such as the browser version, and Operating System.**

**Comment by DALLAR38** [comment]
0x86dd6f9cb1cd08af13a03555cead9854b7bc2dc523bd7bc47e86ec910823f91f

Вернуть на cfx:aakrazy469vpycw6tectrevgh89f262c9awer9wzcm

**Comment by jnoodle** [comment]
I didn't understand what you mean, please try to describe your problem in detail in English.

**Comment by jnoodle** [comment]
No reply for a long time.
