### ISSUE TITLE
как отменить?cfx:acg2vybjvdh6mccjy1ewpfga2k0c4ynzr6x7235212

### ISSUE THREAD

**Issue by DALLAR38** [Conflux-Chain/sirius#378]
**Do you want to request a _feature_ or report a _bug_?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**If this is a associated bounty or submission, please add the url to it here.**

**Please mention other relevant information such as the browser version, and Operating System.**

**Comment by jnoodle** [comment]
Blockchain cannot roll back confirmed transactions. Please carefully confirm the transaction information before submitting the transaction.
