### ISSUE TITLE
Hello. I was going to send a CFX , but I couldn't. Help me recover my CFX coins. Here's txhash:0x8858df6c19f2a86f1248c03c47de2f125c2a45dd3c596c991274c52eea7960fd

### ISSUE THREAD

**Issue by DALLAR38** [Conflux-Chain/sirius#379]
**Do you want to request a _feature_ or report a _bug_?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**If this is a associated bounty or submission, please add the url to it here.**

**Please mention other relevant information such as the browser version, and Operating System.**

**Comment by jnoodle** [comment]
Blockchain cannot roll back confirmed transactions. Please carefully confirm the transaction information before submitting the transaction.
