### ISSUE TITLE
Hi!!! i wanted to ask you for help. i've been sending money to  benance wallet, but they haven't been received.  please, help!!!

### ISSUE THREAD

**Issue by Kissevich** [Conflux-Chain/sirius#380]
**Do you want to request a _feature_ or report a _bug_?**

**What is the current behavior?**

**If the current behavior is a bug, please provide the steps to reproduce.**

**What is the expected behavior?**

**If this is a feature request, what is motivation or use case for changing the behavior?**

**If this is a associated bounty or submission, please add the url to it here.**

**Please mention other relevant information such as the browser version, and Operating System.**

**Comment by Kissevich** [comment]
my wallet Conflux cfx:aas8xhw7nn0vxsx5ff8hen66j9jtsmdvne1xa6kjgn

**Comment by jnoodle** [comment]
Confluxscan is used for blockchain data viewing by users. Only scan-related bugs, technical issues, or product recommendations are accepted here.  For questions about asset and community product usage, please go to the forum or discussion group of the relevant product for help.

https://www.binance.com/en/support
