### ISSUE TITLE
Money

### ISSUE THREAD

**Issue by zevsalex74** [Conflux-Chain/sirius#381]
Hello.
On April 29, 2021, I transferred 97 CFX from the pool to the Binance exchange. But as it turned out, the Binance wallet works in the format of the BSC network and the money was not credited to my account. Binance support encouraged me to contact you for help. How can I get my 97 CFX back?
Transaction number 0xf76bc2e95b43ee8f40ee6a26f92fe0c64cc0f103b519b9199626b8d84af50b2a.

Help me please.

**Comment by Kissevich** [comment]
Мне так и не ответили, у меня такая-же проблема.

**Comment by jnoodle** [comment]
You could refer to:

https://www.binance.com/en/support/announcement/cd4d635399374a68ace90874ce8b9eb2/
https://forum.conflux.fun/t/okex-cfx/6058

You could consult Binance customer service.

**Comment by jnoodle** [comment]
Confluxscan is used for blockchain data viewing by users. Only scan-related bugs, technical issues, or product recommendations are accepted here.  For questions about asset and community product usage, please go to the forum or discussion group of the relevant product for help.

**Comment by AndyBALUTA** [comment]
Have the same problem ,  transaction was from gate.io , status is success, but in https://evm.confluxscan.net/ can’t find my transaction , not find txid and wallet is empty .  The transaction was 2 days ago ! 

Txid : 0x3fe957a58ca791333dd427003caec60c3eafa804c117c7bf8c2f13e3ebb10a09
